 /∗∗∗BasicWificonnection∗∗∗/
#include<WiFi.h>
voidprint_ip_status(){
Serial.print("\nWiFi␣connected␣!\n");
Serial.print("IP␣address:␣");
Serial.println(WiFi.localIP());
Serial.print("MAC␣address:␣");
Serial.println(WiFi.macAddress());
}
voidconnect_wifi(){
//AccessPointoftheinfrastructure
constchar∗ssid="HUAWEI−6EC2";
constchar∗password="FGY9MLBL";
Serial.println("\nConnecting␣Wifi␣to␣");
Serial.println(ssid);
Serial.print("Attempting␣to␣connect␣");
WiFi.begin(ssid,password);
while(WiFi.status()!=WL_CONNECTED){
delay(1000);
Serial.print(".");
}
print_ip_status();
}
voidsetup(){
Serial.begin(9600);
while(!Serial);//waitforaserialconnection

WiFi.mode(WIFI_STA);
WiFi.disconnect();
delay(100);
itwaspreviouslyconnected
connect_wifi();
}
voidloop(){
//nocode
//WiFi.disconnect();
}
